/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Kontakt = {
  _id: string;
  _type: "kontakt";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  naslovSekcije?: LokalniNaslov;
  telefoni?: Array<{
    broj?: string;
    oznaka?: LokalniNaslov;
    _type: "telefon";
    _key: string;
  }>;
  seo?: Seo;
};

export type Advokat = {
  _id: string;
  _type: "advokat";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  ime?: string;
  titula?: LokalniNaslov;
  biografija?: LokalniBlok;
  fotografija?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: LokalniNaslov;
    _type: "image";
  };
  mejl?: string;
  telefon?: string;
  redosled?: number;
};

export type ONama = {
  _id: string;
  _type: "oNama";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  naslovSekcije?: LokalniNaslov;
  tekst?: LokalniBlok;
  statistike?: Array<{
    vrednost?: LokalniNaslov;
    labela?: LokalniNaslov;
    _type: "statistika";
    _key: string;
  }>;
  seo?: Seo;
};

export type Pocetna = {
  _id: string;
  _type: "pocetna";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nadnaslov?: LokalniNaslov;
  naslov?: LokalniNaslov;
  uvodniTekst?: LokalniTekst;
  tekstDugmeta?: LokalniNaslov;
  linkDugmeta?: string;
  seo?: Seo;
};

export type Podesavanja = {
  _id: string;
  _type: "podesavanja";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nazivKancelarije?: string;
  adresa?: {
    ulica?: string;
    grad?: LokalniNaslov;
    drzava?: LokalniNaslov;
  };
  koordinate?: {
    lat?: number;
    lng?: number;
  };
  opstiTelefon?: string;
  opstiMejl?: string;
  adresaSajta?: string;
  radnoVreme?: LokalniTekst;
  pib?: string;
  advokatskaKomora?: LokalniNaslov;
};

export type Seo = {
  _type: "seo";
  naslov?: LokalniNaslov;
  opis?: LokalniTekst;
  ogSlika?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type LokalniBlok = {
  _type: "lokalniBlok";
  sr?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  en?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type LokalniTekst = {
  _type: "lokalniTekst";
  sr?: string;
  en?: string;
};

export type LokalniNaslov = {
  _type: "lokalniNaslov";
  sr?: string;
  en?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Kontakt | Advokat | ONama | Pocetna | Podesavanja | Seo | LokalniBlok | LokalniTekst | LokalniNaslov | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: CONTENT_QUERY
// Query: {  "podesavanja": *[_type == "podesavanja"][0]{...},  "pocetna": *[_type == "pocetna"][0]{...},  "oNama": *[_type == "oNama"][0]{...},  "advokati": *[_type == "advokat"] | order(redosled asc){...},  "kontakt": *[_type == "kontakt"][0]{...}}
export type CONTENT_QUERYResult = {
  podesavanja: {
    _id: string;
    _type: "podesavanja";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    nazivKancelarije?: string;
    adresa?: {
      ulica?: string;
      grad?: LokalniNaslov;
      drzava?: LokalniNaslov;
    };
    koordinate?: {
      lat?: number;
      lng?: number;
    };
    opstiTelefon?: string;
    opstiMejl?: string;
    adresaSajta?: string;
    radnoVreme?: LokalniTekst;
    pib?: string;
    advokatskaKomora?: LokalniNaslov;
  } | null;
  pocetna: {
    _id: string;
    _type: "pocetna";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    nadnaslov?: LokalniNaslov;
    naslov?: LokalniNaslov;
    uvodniTekst?: LokalniTekst;
    tekstDugmeta?: LokalniNaslov;
    linkDugmeta?: string;
    seo?: Seo;
  } | null;
  oNama: {
    _id: string;
    _type: "oNama";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    naslovSekcije?: LokalniNaslov;
    tekst?: LokalniBlok;
    statistike?: Array<{
      vrednost?: LokalniNaslov;
      labela?: LokalniNaslov;
      _type: "statistika";
      _key: string;
    }>;
    seo?: Seo;
  } | null;
  advokati: Array<{
    _id: string;
    _type: "advokat";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    ime?: string;
    titula?: LokalniNaslov;
    biografija?: LokalniBlok;
    fotografija?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: LokalniNaslov;
      _type: "image";
    };
    mejl?: string;
    telefon?: string;
    redosled?: number;
  }>;
  kontakt: {
    _id: string;
    _type: "kontakt";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    naslovSekcije?: LokalniNaslov;
    telefoni?: Array<{
      broj?: string;
      oznaka?: LokalniNaslov;
      _type: "telefon";
      _key: string;
    }>;
    seo?: Seo;
  } | null;
};
// Variable: SETTINGS_QUERY
// Query: *[_type == "podesavanja"][0]{...}
export type SETTINGS_QUERYResult = {
  _id: string;
  _type: "podesavanja";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nazivKancelarije?: string;
  adresa?: {
    ulica?: string;
    grad?: LokalniNaslov;
    drzava?: LokalniNaslov;
  };
  koordinate?: {
    lat?: number;
    lng?: number;
  };
  opstiTelefon?: string;
  opstiMejl?: string;
  adresaSajta?: string;
  radnoVreme?: LokalniTekst;
  pib?: string;
  advokatskaKomora?: LokalniNaslov;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "{\n  \"podesavanja\": *[_type == \"podesavanja\"][0]{...},\n  \"pocetna\": *[_type == \"pocetna\"][0]{...},\n  \"oNama\": *[_type == \"oNama\"][0]{...},\n  \"advokati\": *[_type == \"advokat\"] | order(redosled asc){...},\n  \"kontakt\": *[_type == \"kontakt\"][0]{...}\n}": CONTENT_QUERYResult;
    "\n  *[_type == \"podesavanja\"][0]{...}\n": SETTINGS_QUERYResult;
  }
}
